### ISSUE TITLE
Check whether coq-community would be interested in some of these proofs

### ISSUE THREAD

**Issue by gallais** [coqtail/coqtail#1]
I see that the stdlib still has Ranalysis1..5 so maybe our work is still relevant
to coq users?

https://github.com/coq-community

**Comment by palmskog** [comment]
@gallais @jmadiot this project would indeed be very welcome in coq-community, and the members of the community could assist with things like:
- defining an opam package
- setting up continuous integration
- setting up automation for publishing library releases
- writing documentation

Please consider [making an issue](https://github.com/coq-community/manifesto/issues/new?labels=move-project&template=1-move-a-project.md&title=Proposal+to+move+project+Coqtail+to+coq-community) to transfer the project to the coq-community GitHub organization. See also the documentation for [proposing a new package](https://github.com/coq-community/manifesto/blob/master/CONTRIBUTING.md#proposing-a-new-package).

**Comment by jmadiot** [comment]
Coqtail is now [part of coq-community](https://github.com/coq-community/coqtail-math). Note that only the development directory `src`, after cleanup, has been transferred.
