### ISSUE TITLE
Setting `fo+=r` yield reinsertion of comments on Enter

### ISSUE THREAD

**Issue by dhilst** [coqtail/coqtail#2]
Hello! 

First of all thanks for bringing Coq to vim, I've been using it for a while and it works like a charm.

The only thing that is annoying is the comment problem with `fo+=r` option. I use that option because I think it makes it easier to comment and makes comments prettier too.

I think I managed to get it working using this `comments` value

```
  setlocal comments=sO:*\ -,mO:*\ \ ,exO:*),s1:(*,mb:*,ex:*)
```

It will add `*` at the beginning of the line automatically which I think is nice, leading to comments like this: 

<img width="249" alt="image" src="https://user-images.githubusercontent.com/392820/153328518-6c10368d-317f-4c7c-8a57-1bd66afd81ab.png">

I can open a pull request if you want

Regards,

**Comment by gallais** [comment]
\**waves hand*\* This is not the coqtail you're looking for

Cf. https://github.com/whonore/Coqtail

**Comment by dhilst** [comment]
Oh, sorry! 🤦
